@extends('layouts.app')

@section('title', 'Review Draft Final Hasil Fasilitasi')

@section('main')
    <div class="container-xxl flex-grow-1 container-p-y">
        <!-- Header -->
        <div class="d-flex justify-content-between align-items-center mb-4">
            <div>
                <h4 class="fw-bold mb-1">Review Draft Final Hasil Fasilitasi</h4>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb breadcrumb-style1 mb-0">
                        <li class="breadcrumb-item"><a href="{{ route('dashboard') }}">Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('approval.index') }}">Persetujuan</a></li>
                        <li class="breadcrumb-item active">Review</li>
                    </ol>
                </nav>
            </div>
            <a href="{{ route('approval.index') }}" class="btn btn-outline-secondary">
                <i class="bx bx-arrow-back me-1"></i> Kembali
            </a>
        </div>

        <div class="row">
            <!-- Draft Final & Info -->
            <div class="col-lg-8 mb-4">
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="card-title mb-3">
                            <i class="bx bx-file-find me-2"></i> Draft Final Hasil Fasilitasi
                        </h5>

                        <div class="row g-3">
                            <div class="col-md-6">
                                <label class="form-label text-muted small mb-1">Kabupaten/Kota</label>
                                <p class="fw-bold mb-0">{{ $permohonan->kabupatenKota->getFullNameAttribute() ?? '-' }}</p>
                            </div>
                            <div class="col-md-6">
                                <label class="form-label text-muted small mb-1">Jenis Dokumen</label>
                                <p class="fw-bold mb-0">{{ $permohonan->jenisDokumen->nama ?? '-' }}</p>
                            </div>
                            <div class="col-md-6">
                                <label class="form-label text-muted small mb-1">Tanggal Diajukan</label>
                                <p class="mb-0">
                                    @if ($hasilFasilitasi && $hasilFasilitasi->tanggal_diajukan_kaban)
                                        {{ $hasilFasilitasi->tanggal_diajukan_kaban->format('d M Y H:i') }}
                                    @else
                                        -
                                    @endif
                                </p>
                            </div>
                        </div>

                        <hr class="my-3">

                        <!-- Draft File (Word/PDF generated by system) -->
                        @if ($hasilFasilitasi && $hasilFasilitasi->draft_file)
                            <div class="mb-3">
                                <div class="d-flex justify-content-between align-items-center">
                                    <div>
                                        <label class="form-label text-muted small mb-1">File Draft (Hasil Generate)</label>
                                        <p class="mb-0">
                                            <i class="bx bx-file text-primary me-1"></i>
                                            <span class="text-muted small">Draft yang di-generate oleh sistem</span>
                                        </p>
                                    </div>
                                    <div class="btn-group">
                                        <a href="{{ route('hasil-fasilitasi.download-word', $permohonan) }}" target="_blank"
                                            class="btn btn-sm btn-outline-primary">
                                            <i class="bx bx-download me-1"></i> Word
                                        </a>
                                        <a href="{{ route('hasil-fasilitasi.download-pdf', $permohonan) }}" target="_blank"
                                            class="btn btn-sm btn-outline-primary">
                                            <i class="bx bx-download me-1"></i> PDF
                                        </a>
                                    </div>
                                </div>
                            </div>
                        @endif

                        <!-- Draft Final File (Uploaded with letterhead) -->
                        <div class="d-flex justify-content-between align-items-center">
                            <div>
                                <label class="form-label text-muted small mb-1">File Draft Final (Dilengkapi Kop Surat)</label>
                                @if ($hasilFasilitasi && $hasilFasilitasi->draft_final_file)
                                    <p class="mb-0">
                                        <i class="bx bx-file-pdf text-danger me-1"></i>
                                        <span class="text-muted small">Diupload:
                                            {{ $hasilFasilitasi->updated_at->format('d M Y H:i') }}</span>
                                    </p>
                                @else
                                    <p class="mb-0 text-muted">Draft final belum tersedia</p>
                                @endif
                            </div>
                            @if ($hasilFasilitasi && $hasilFasilitasi->draft_final_file)
                                <a href="{{ route('approval.download-draft-final', $permohonan) }}" target="_blank"
                                    class="btn btn-primary">
                                    <i class="bx bx-download me-1"></i> Download PDF Final
                                </a>
                            @endif
                        </div>

                        @if ($hasilFasilitasi && $hasilFasilitasi->catatan_fasilitator)
                            <div class="alert alert-light border mt-3 mb-0">
                                <small class="text-muted d-block mb-1"><strong>Catatan Fasilitator:</strong></small>
                                <p class="mb-0 small">{!! nl2br(e($hasilFasilitasi->catatan_fasilitator)) !!}</p>
                            </div>
                        @endif
                    </div>
                </div>

                <!-- Tim Fasilitasi -->
                @if ($timInfo)
                    <div class="card">
                        <div class="card-body">
                            <h6 class="card-title mb-3">
                                <i class="bx bx-group me-1"></i> Tim Fasilitasi
                            </h6>
                            <ul class="list-unstyled mb-0">
                                @if ($timInfo['verifikator'])
                                    <li class="mb-2">
                                        <i class="bx bx-user-check text-info me-1"></i>
                                        <strong>Verifikator:</strong>
                                        {{ $timInfo['verifikator']->user->name ?? '-' }}
                                    </li>
                                @endif

                                @if ($timInfo['koordinator'])
                                    <li class="mb-2">
                                        <i class="bx bx-user-check text-primary me-1"></i>
                                        <strong>Koordinator:</strong>
                                        {{ $timInfo['koordinator']->user->name ?? '-' }}
                                    </li>
                                @endif

                                @if ($timInfo['anggota'] && $timInfo['anggota']->count() > 0)
                                    <li>
                                        <i class="bx bx-group text-secondary me-1"></i>
                                        <strong>Anggota:</strong>
                                        @foreach ($timInfo['anggota'] as $anggota)
                                            {{ $anggota->user->name ?? '-' }}@if (!$loop->last)
                                                ,
                                            @endif
                                        @endforeach
                                    </li>
                                @endif
                            </ul>
                        </div>
                    </div>
                @endif
            </div>

            <!-- Form Approval -->
            <div class="col-lg-4">
                <div class="alert alert-info mb-3">
                    <i class="bx bx-info-circle me-1"></i>
                    <small>
                        <strong>Info:</strong> Dengan menyetujui, tahapan hasil fasilitasi akan diselesaikan dan tahapan
                        berikutnya akan dimulai otomatis.
                    </small>
                </div>

                <!-- Approve Card -->
                <div class="card border-success mb-3">
                    <div class="card-body">
                        <h6 class="text-success mb-3">
                            <i class="bx bx-check-circle me-1"></i> Setujui Dokumen
                        </h6>
                        <form action="{{ route('approval.approve', $permohonan) }}" method="POST">
                            @csrf
                            <button type="submit" class="btn btn-success w-100"
                                onclick="return confirm('Yakin menyetujui dokumen ini?')">
                                <i class="bx bx-check-circle me-1"></i> Setujui
                            </button>
                        </form>
                    </div>
                </div>

                <!-- Reject Card -->
                <div class="card border-danger">
                    <div class="card-body">
                        <h6 class="text-danger mb-2">
                            <i class="bx bx-x-circle me-1"></i> Minta Revisi
                        </h6>
                        <p class="small text-muted mb-3">Admin/Koordinator perlu upload ulang draft final yang sudah
                            diperbaiki</p>
                        <button type="button" class="btn btn-danger w-100" data-bs-toggle="modal"
                            data-bs-target="#rejectModal">
                            <i class="bx bx-x-circle me-1"></i> Minta Revisi
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Reject Modal -->
    <div class="modal fade" id="rejectModal" tabindex="-1" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header bg-danger">
                    <h5 class="modal-title text-white">
                        <i class="bx bx-error-circle me-1"></i> Minta Revisi Dokumen
                    </h5>
                    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"
                        aria-label="Close"></button>
                </div>
                <form action="{{ route('approval.reject', $permohonan) }}" method="POST">
                    @csrf
                    <div class="modal-body">
                        <div class="alert alert-warning">
                            <i class="bx bx-info-circle me-1"></i>
                            <strong>Catatan:</strong> Admin dan koordinator akan menerima notifikasi untuk melakukan
                            perbaikan dan upload ulang draft final.
                        </div>

                        <div class="mb-3">
                            <label class="form-label">Catatan Revisi <span class="text-danger">*</span></label>
                            <textarea class="form-control @error('catatan_penolakan') is-invalid @enderror" name="catatan_penolakan"
                                rows="5" required placeholder="Jelaskan secara detail perbaikan/revisi yang diperlukan..."></textarea>
                            @error('catatan_penolakan')
                                <div class="invalid-feedback">{{ $message }}</div>
                            @enderror
                            <small class="text-muted">
                                Jelaskan dengan jelas bagian mana yang perlu diperbaiki
                            </small>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
                            <i class="bx bx-x me-1"></i> Batal
                        </button>
                        <button type="submit" class="btn btn-danger"
                            onclick="return confirm('Yakin mengembalikan dokumen untuk revisi?')">
                            <i class="bx bx-send me-1"></i> Kirim Permintaan Revisi
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection
